SELECT EMPLOYEE.Fname, EMPLOYEE.Minit, EMPLOYEE.Lname, EMPLOYEE2.Fname AS Super_Fname, EMPLOYEE2.Minit AS Super_Minit, EMPLOYEE2.Lname AS Super_Lname, Dname, Dlocation
FROM EMPLOYEE, EMPLOYEE AS EMPLOYEE2, DEPARTMENT, DEPT_LOCATIONS
WHERE EMPLOYEE.Super_ssn=EMPLOYEE2.Ssn AND EMPLOYEE.DNO=DEPARTMENT.Dnumber AND DEPARTMENT.Dnumber=DEPT_LOCATIONS.Dnumber AND EMPLOYEE.Sex="M";
