SELECT Fname, Minit, Lname, Dname, Dlocation
FROM EMPLOYEE, (SELECT Dname, Dlocation, DEPARTMENT.Dnumber
FROM DEPARTMENT, DEPT_LOCATIONS
WHERE DEPARTMENT.Dnumber=DEPT_LOCATIONS.Dnumber) AS TEMP
WHERE EMPLOYEE.Dno=TEMP.Dnumber;
