SELECT Dname FROM 
(SELECT Dname, COUNT(Essn) AS Num_Dependents
FROM EMPLOYEE, DEPENDENT, DEPARTMENT
WHERE EMPLOYEE.Dno=DEPARTMENT.Dnumber AND EMPLOYEE.Ssn=DEPENDENT.Essn
GROUP BY Dname) AS TEMP
WHERE Num_Dependents>1;