SELECT Fname, Minit, Lname, Ssn
FROM EMPLOYEE, DEPARTMENT, DEPT_LOCATIONS
WHERE EMPLOYEE.Dno=DEPARTMENT.Dnumber 
AND DEPT_LOCATIONS.Dnumber=DEPARTMENT.Dnumber AND Dlocation="Houston" AND EMPLOYEE.SSN NOT IN
(
    SELECT Essn 
    FROM PROJECT, WORKS_ON
    WHERE Pno=Pnumber AND Plocation="Houston"
);